# Generated by Django 2.1.5 on 2019-02-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.BooleanField(default=False),
        ),
    ]
